# Generated by Django 5.2.17 on 2026-10-07 13:02

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_place_and_time_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='has_page_on_site',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_registration_available',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_translation_alive',
        ),
        migrations.RemoveField(
            model_name='event',
            name='place_and_time_html',
        ),
        migrations.RemoveField(
            model_name='event',
            name='register_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='translation_video_code',
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_html',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='none', editable=False),
        ),
    ]
