language: python
python:
  - "3.13"
install: pip install -r requirements-dev.txt
script:
  - python manage.py check
  - python manage.py makemigrations --check --dry-run
  - pytest --cov=apps --cov=python_ru
