[tox]
envlist = py313
skipsdist = true

[testenv]
deps = -r requirements-dev.txt
setenv =
    DJANGO_SETTINGS_MODULE = python_ru.settings.development
    DATABASE_URL = sqlite:///:memory:
commands =
    python manage.py check
    python manage.py makemigrations --check --dry-run
    pytest --cov=apps --cov=python_ru

[pytest]
DJANGO_SETTINGS_MODULE = python_ru.settings.development
python_files = test_*.py *_test.py
