# Generated by Django 5.2.17 on 2026-10-07 13:02

from django.db import migrations


def remove_retired_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Permission.objects.using(schema_editor.connection.alias).filter(
        content_type__app_label='meetups',
        content_type__model__in=['talk', 'speaker', 'employer'],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_auto_20180225_2107'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(remove_retired_permissions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='speaker',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='event',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.DeleteModel(
            name='Talk',
        ),
    ]
