# Generated by Django 2.0.1 on 2018-06-28 09:55

import apps.content.legacy_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180113_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('ru', '🇷🇺'), ('en', '🇬🇧')], max_length=2, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=apps.content.legacy_fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
