# Generated by Django 2.0.13 on 2026-10-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180628_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='kind',
            field=models.CharField(choices=[('article', 'Статья'), ('translation', 'Перевод'), ('interview', 'Интервью'), ('news', 'Новость'), ('note', 'Заметка')], default='article', max_length=20, verbose_name='Тип материала'),
        ),
        migrations.AddField(
            model_name='article',
            name='reading_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время чтения, минут'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=300, verbose_name='Теги через запятую'),
        ),
    ]
