# Generated by Django 5.2.17 on 2026-10-06 12:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20261006_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Текст'),
        ),
    ]
