# Generated by Django 5.2.17 on 2026-10-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_article_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-id'], 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
    ]
