# Generated by Django 2.0.13 on 2026-10-06 12:17

import apps.content.legacy_fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('city', models.CharField(max_length=100, verbose_name='Город или регион')),
                ('members', models.PositiveIntegerField(blank=True, null=True, verbose_name='Участники (необязательно)')),
            ],
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Сообщества',
                'ordering': ['position', 'name', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('article', 'Статья'), ('event', 'Событие'), ('project', 'Проект'), ('community', 'Сообщество')], max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('name', models.CharField(max_length=120, verbose_name='Ваше имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для ответа')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('review', 'На рассмотрении'), ('done', 'Обработано')], default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения читателей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('body', apps.content.legacy_fields.RichTextUploadingField(verbose_name='Содержимое письма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Выпуск дайджеста',
                'verbose_name_plural': 'Выпуски дайджеста',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', apps.content.legacy_fields.RichTextUploadingField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Категория')),
                ('stars', models.PositiveIntegerField(blank=True, null=True, verbose_name='Звёзды GitHub (необязательно)')),
            ],
            options={
                'verbose_name': 'Open Source проект',
                'verbose_name_plural': 'Open Source проекты',
                'ordering': ['position', 'name', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Подписан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='digest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Digest'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Subscriber'),
        ),
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together={('digest', 'subscriber')},
        ),
    ]
