# Generated by Django 5.2.17 on 2026-10-06 12:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_initial_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digest',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержимое письма'),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст'),
        ),
    ]
