# Generated by Django 5.2.17 on 2026-10-07 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_deliveries(apps, schema_editor):
    alias = schema_editor.connection.alias
    Delivery = apps.get_model('portal', 'Delivery')
    Digest = apps.get_model('portal', 'Digest')
    for delivery in Delivery.objects.using(alias).select_related('subscriber').iterator():
        delivery.email = delivery.subscriber.email
        delivery.state = 'sent'
        delivery.save(using=alias, update_fields=['email', 'state'])
    Digest.objects.using(alias).filter(sent_at__isnull=False).update(state='sent')
    # A partially sent legacy issue also stays closed; copying creates a deliberate new issue.
    Digest.objects.using(alias).filter(delivery__isnull=False).update(state='sent')


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_has_page_on_site_and_more'),
        ('news', '0010_alter_article_options'),
        ('portal', '0003_alter_digest_body_alter_page_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestWorker',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('heartbeat', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставки'},
        ),
        migrations.AlterModelOptions(
            name='digest',
            options={'permissions': [('send_digest', 'Может отправлять дайджесты')], 'verbose_name': 'Выпуск дайджеста', 'verbose_name_plural': 'Выпуски дайджеста'},
        ),
        migrations.AddField(
            model_name='contribution',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.article'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.community'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.event'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='internal_note',
            field=models.TextField(blank=True, verbose_name='Внутренний комментарий'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.project'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='attempted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='claim',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Адрес на момент запуска'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='error',
            field=models.TextField(blank=True, verbose_name='Ошибка'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='state',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('sending', 'Отправляется'), ('sent', 'Доставлено'), ('skipped', 'Отписался'), ('failed', 'Ошибка'), ('uncertain', 'Результат неизвестен')], default='pending', max_length=12, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='digest',
            name='queued_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Поставлен в очередь'),
        ),
        migrations.AddField(
            model_name='digest',
            name='state',
            field=models.CharField(choices=[('draft', 'Черновик'), ('queued', 'В очереди'), ('sending', 'Отправляется'), ('attention', 'Требует внимания'), ('sent', 'Отправлен')], default='draft', max_length=12, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доставлено'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.subscriber'),
        ),
        migrations.RunPython(preserve_deliveries, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['state', 'id'], name='delivery_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('article__isnull', True), ('event__isnull', True), ('project__isnull', True)), models.Q(('article__isnull', True), ('community__isnull', True), ('event__isnull', True)), models.Q(('article__isnull', True), ('community__isnull', True), ('project__isnull', True)), models.Q(('community__isnull', True), ('event__isnull', True), ('project__isnull', True)), _connector='OR'), name='contribution_at_most_one_target'),
        ),
    ]
