# Generated by Django 5.2.17 on 2026-04-01

from django.db import migrations, models
import django.core.validators


SLOT_POSITIONS = (
    ('top', 'Под шапкой'),
    ('sidebar', 'В сайдбаре главной страницы'),
    ('article_end', 'После статьи'),
    ('bottom', 'Перед подвалом'),
)


def copy_positions_and_seed_slots(apps, schema_editor):
    Banner = apps.get_model('banners', 'Banner')
    Position = apps.get_model('banners', 'Position')

    # Copy before removing the legacy ForeignKey, retaining every association.
    for banner in Banner.objects.exclude(position_id=None).iterator():
        banner.positions.add(banner.position_id)

    # Tags were never unique.  Leave all existing rows untouched and ensure
    # that each human-readable canonical slot is available for new banners.
    for tag, name in SLOT_POSITIONS:
        if not Position.objects.filter(tag=tag, name=name).exists():
            Position.objects.create(tag=tag, name=name)


def keep_seeded_slots_on_reverse(apps, schema_editor):
    # A tag is deliberately not unique, so a pre-existing legacy row can be
    # indistinguishable from a seeded one.  Keeping these rows is the only
    # lossless reverse operation.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='tag',
            field=models.CharField(max_length=32, verbose_name='Тег места размещения'),
        ),
        migrations.AddField(
            model_name='banner',
            name='positions',
            field=models.ManyToManyField(to='banners.position', verbose_name='Места размещения баннера'),
        ),
        migrations.RunPython(copy_positions_and_seed_slots, keep_seeded_slots_on_reverse),
        migrations.RemoveField(
            model_name='banner',
            name='position',
        ),
        migrations.AlterField(
            model_name='banner',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность баннера'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='date_to',
            field=models.DateField(blank=True, help_text='Не заполняйте для показа без ограничения. В эту дату баннер ещё показывается.', null=True, verbose_name='Дата окончания показа баннеров'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='date_time_from',
            field=models.IntegerField(default=0, help_text='От 0 до 23 включительно.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Час начала показа каждый указанный день'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='date_time_to',
            field=models.IntegerField(default=24, help_text='От 1 до 24 включительно; этот час уже не входит в показ.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Час окончания показа каждый указанный день'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='height',
            field=models.CharField(blank=True, help_text='Положительное целое значение в px или %, например 200px или 100%.', max_length=7, validators=[django.core.validators.RegexValidator(message='Укажите положительное целое значение в px или % (например, 300px или 100%).', regex='^[1-9]\\d*(?:px|%)$')], verbose_name='Высота отображения баннера'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_to',
            field=models.URLField(help_text='Только абсолютная ссылка с http или https.', max_length=255, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Ссылка перехода'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='priority',
            field=models.IntegerField(default=50, help_text='Выше число — выше приоритет.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Приоритет показа от 1 до 100'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='width',
            field=models.CharField(blank=True, help_text='Положительное целое значение в px или %, например 720px или 100%.', max_length=7, validators=[django.core.validators.RegexValidator(message='Укажите положительное целое значение в px или % (например, 300px или 100%).', regex='^[1-9]\\d*(?:px|%)$')], verbose_name='Ширина отображения баннера'),
        ),
    ]
